# Add this block at the top level of your workflow file...
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    # ... OR add it directly under your job like this:
    # permissions:
    #   contents: write
    steps:
      # ... your steps ...
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        # ...
